### ISSUE TITLE
clear highlighting

### ISSUE THREAD

**Issue by itchyny** [vimtaku/hl_matchit.vim#1]
カーソルが動いたら, 解除しなければいけないと思います.
![a](https://f.cloud.github.com/assets/375258/45034/e09beec2-5737-11e2-8eaf-511afcad3d45.png)
if hogeがhighlightされた状態で, jで下に行くと
![b](https://f.cloud.github.com/assets/375258/45035/e679da34-5737-11e2-95af-610231d9be20.png)
となり, if hogeがハイライトされたままになってしまいます.

![c](https://f.cloud.github.com/assets/375258/45052/1fc8f398-573c-11e2-8ca7-9e1eba9de110.png)
下に行くと...
![d](https://f.cloud.github.com/assets/375258/45053/23680ade-573c-11e2-9bd1-13d65cf23996.png)

```
    diff --git a/autoload/hl_matchit.vim b/autoload/hl_matchit.vim
    index 1cc940b..0eee90d 100644
    --- a/autoload/hl_matchit.vim
    +++ b/autoload/hl_matchit.vim
    @@ -17,6 +17,9 @@ function! hl_matchit#do_highlight()
            endif
         endif

    +    exe 'match '. g:hl_matchit_hl_groupname . " ''"
    +    match none
    +
         let l = getline('.')
         if g:hl_matchit_speed_level <= s:SPEED_MOST_IMPORTANT
             if l =~ '[(){}]'
```

**Comment by vimtaku** [comment]
ご報告ありがとうございます。
修正致しました。
https://github.com/vimtaku/hl_matchit.vim/commit/e1def224f36530a4eb9ee342ffca6d633182cc1d

以上、よろしくお願いします。

**Comment by itchyny** [comment]
確認しました. ありがとうございます.
