### ISSUE TITLE
visual mode, %で選択できない

### ISSUE THREAD

**Issue by itchyny** [vimtaku/hl_matchit.vim#2]
ifからendifまでを選択するときに, ifの所でline visual→%で選択したいのですが, 一度endifにカーソルが飛んで戻ってきます.

**Comment by vimtaku** [comment]
本件、確認できました。
しばらく試行錯誤したのですが原因が分からないのでとりあえず対応を保留します。
原因お分かりでしたら pull req ください。

以上、よろしくおねがいします。

**Comment by vimtaku** [comment]
とりあえず gv で一時的な対応は出来たみたいなのでそのようにしています。
これは応急処置で、根本解決ではないので、引き続き原因お分かりでしたら pull req ください。

以上、よろしくおねがいします。

**Comment by itchyny** [comment]
チラツキますが, 選択できるようになったことは確認しました.
